name: ff_commons
description: FlutterFlow Commons Package

publish_to: 'none'

version: 1.1.1+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  ezecom:
    path: ../../
  collection: 1.19.1
  equatable: 2.0.7
  http: 1.4.0
  mime_type: 1.0.0

dependency_overrides:
  device_info_plus: 11.5.0
  device_info_plus_platform_interface: 7.0.3
  http: 1.4.0
  rxdart: 0.27.7
  uuid: ^4.0.0


flutter:
